/* MatchIQ Scout - Storage Module V8.0.3 Hotfix 3 */
function toggleWatchlistById(id){ if(!canUseWatchlist()){toast("Watchlist PRO","La watchlist Scout è disponibile solo per Pro/Owner.");return;} const p=state.players.find(x=>String(x.id)===String(id)); if(!p)return; if(isWatched(id)){removeWatchlist(id);toast("Rimosso dalla watchlist",p.name);}else{addWatchlist(p);toast("Aggiunto alla watchlist",p.name);} renderAll(); }
function addOpenPlayerToWatchlist(){ if(!canUseWatchlist()){toast("Watchlist PRO","Disponibile solo per Pro/Owner.");return;} const p=state.players.find(x=>String(x.id)===String(state.openPlayerId)); if(!p)return; addWatchlist(p); renderAll(); renderModal(); toast("Aggiunto alla watchlist",p.name); }
function removeOpenPlayerFromWatchlist(){ if(!canUseWatchlist())return; if(!state.openPlayerId)return; removeWatchlist(state.openPlayerId); renderAll(); renderModal(); }
function addWatchlist(p){ if(!p||!p.id||isWatched(p.id))return; const verdict=typeof scoutVerdict==="function"?scoutVerdict(p):null; state.watchlist.push({id:p.id,name:p.name,team:p.team,role:p.role,scout_score:p.scout_score,threat:p.threat,creativity:p.creativity,pressure:p.pressure,momentum:p.momentum,signal:p.signal,data_source:p.data_source,verdict_label:verdict?.label||"",verdict_reason:verdict?.reason||"",saved_at:new Date().toISOString()}); saveWatchlist(); }
function removeWatchlist(id){ state.watchlist=state.watchlist.filter(p=>String(p.id)!==String(id)); saveWatchlist(); }
function clearWatchlist(){ if(!canUseWatchlist()){toast("Watchlist PRO","Disponibile solo per Pro/Owner.");return;} state.watchlist=[]; saveWatchlist(); renderAll(); toast("Watchlist svuotata","Tutti i giocatori salvati sono stati rimossi."); }
function isWatched(id){ return state.watchlist.some(p=>String(p.id)===String(id)); }
function loadWatchlist(){ try{ const raw=localStorage.getItem(STORAGE_KEY); const parsed=JSON.parse(raw||"[]"); return Array.isArray(parsed)?parsed.filter(p=>p&&p.id):[];}catch{return [];} }
function saveWatchlist(){ try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state.watchlist||[]));}catch{toast("Errore salvataggio","Non riesco a salvare la watchlist nel browser.");} }
function exportWatchlist(){ if(!canExportScout()){toast("Export PRO","Export disponibile solo per Pro/Owner.");return;} if(!state.watchlist.length){toast("Watchlist vuota","Non ci sono player da esportare.");return;} const rows=["Nome;Squadra;Ruolo;Score;Threat;Creativity;Pressure;Momentum;Signal;Source;SavedAt",...state.watchlist.map(p=>[csv(p.name),csv(p.team),csv(p.role),Math.round(num(p.scout_score,0)),Math.round(num(p.threat,0)),Math.round(num(p.creativity,0)),Math.round(num(p.pressure,0)),Math.round(num(p.momentum,0)),csv(p.signal),csv(p.data_source),csv(p.saved_at||"")].join(";"))]; downloadText("matchiq_watchlist_v803.csv",rows.join("\n")); }
function exportScoutReport(){ if(!canExportScout()){toast("Export PRO","Report Scout disponibile solo per Pro/Owner.");return;} if(!state.players.length){toast("Nessun dato","Non ci sono player reali da esportare.");return;} const m=getMatch(); const topPlayers=[...state.players].sort((a,b)=>num(b.scout_score,0)-num(a.scout_score,0)).slice(0,15); const report=["MATCHIQ SCOUT V8.0.3 REPORT","==========================","",`Match: ${m?`${m.home} - ${m.away}`:"--"}`,`Score: ${m?`${m.scoreHome}-${m.scoreAway}`:"--"}`,`Minuto: ${m?m.minute+"'":"--"}`,`Status: ${m?m.status:"--"}`,`Generato: ${new Date().toLocaleString("it-IT")}`,"","SUMMARY","-------",`Players reali: ${state.players.length}`,`Eventi timeline: ${state.events.length}`,`Watchlist: ${state.watchlist.length}`,"","TOP PLAYERS","-----------",...topPlayers.map((p,i)=>`${i+1}. ${p.name} | ${p.team} | ${p.role} | Score ${Math.round(num(p.scout_score,0))} | Threat ${Math.round(num(p.threat,0))} | Creativity ${Math.round(num(p.creativity,0))} | Pressure ${Math.round(num(p.pressure,0))} | ${p.signal} | ${p.data_source}`)].join("\n"); downloadText("matchiq_scout_report_v803.txt",report); }
function exportOpenPlayerReport(){ if(!canExportScout()){toast("Export PRO","Player report disponibile solo per Pro/Owner.");return;} const p=state.players.find(x=>String(x.id)===String(state.openPlayerId)); if(!p)return; const playerEvents=state.events.filter(e=>String(e.playerId)===String(p.id)||e.playerName===p.name); const report=["MATCHIQ PLAYER SCOUT REPORT V8.0.3","=================================","",`Giocatore: ${p.name}`,`Squadra: ${p.team}`,`Ruolo: ${p.role}`,`Data source: ${p.data_source}`,`Data quality: ${p.data_quality}`,"","METRICHE","-------",`Scout Score: ${Math.round(num(p.scout_score,0))}`,`Impact Score: ${Math.round(num(p.impact_score,0))}`,`Threat: ${Math.round(num(p.threat,0))}%`,`Creativity: ${Math.round(num(p.creativity,0))}%`,`Pressure: ${Math.round(num(p.pressure,0))}%`,`Momentum: ${Math.round(num(p.momentum,0))}%`,`Stamina: ${Math.round(num(p.stamina,0))}%`,"","AI COMMENTARY","-------------",p.ai_summary||aiComment(p),"","EVENTI PLAYER","-------------",...(playerEvents.length?playerEvents.map(e=>`${e.minute}' ${e.label} - ${e.title}: ${e.desc}`):["Nessun evento specifico disponibile."])].join("\n"); downloadText(`matchiq_player_${safeFilename(p.name)}_v803.txt`,report); }
function downloadText(filename,text){ const blob=new Blob([text],{type:"text/plain;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=filename; document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url); toast("Export completato",filename); }
function csv(v){ return `"${String(v??"").replaceAll('"','""')}"`; }
function safeFilename(v){ return String(v||"player").toLowerCase().replace(/[^a-z0-9]+/gi,"_").replace(/^_+|_+$/g,""); }
